### ISSUE TITLE
No cravat-system.yml file and packagedir is not defined errors during installation

### ISSUE THREAD

**Issue by Alex-Karmazin** [rkimoakbioinformatics/oakvar#1]
I install oakvar on linux (Ubuntu 20.04.3 LTS) under micromamba with command "pip install oakvar" then I use command "oc module installbase" and get error there is no file cravat-system.yml. I found cravat-system.template.yml and renamed it. Then "oc module installbase" start getting different error.
"""
Traceback (most recent call last):
  File "/home/alex/micromamba/envs/opencravat-longevity/bin/oc", line 5, in <module>
    from oakvar.__main__ import main
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/oakvar/__init__.py", line 52, in <module>
    from . import __main__ as cli
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/oakvar/__main__.py", line 5, in <module>
    from .cli_gui import get_parser_fn_gui
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/oakvar/cli_gui.py", line 9, in <module>
    sysconf = get_system_conf()
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/oakvar/admin_util.py", line 939, in get_system_conf
    conf[modules_dir_key] = get_default_modules_dir()
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/oakvar/admin_util.py", line 2005, in get_default_modules_dir
    return pathjoin(get_ov_root_dir(), modules_dir_name)
  File "/home/alex/micromamba/envs/opencravat-longevity/lib/python3.9/site-packages/oakvar/admin_util.py", line 1886, in get_ov_root_dir
    root_dir = packagedir
NameError: name 'packagedir' is not defined
"""

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin I'll look into it.

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin I'm fixing the issue. While doing so, the setup process is being improved, so that ``ov system setup`` will do all the setup processes. The new version will be released shortly.

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin OakVar v2.4.2 has been released (release note at https://github.com/rkimoakbioinformatics/oakvar/releases/tag/2.4.2). Let me know if it solves the issue. Details of ``ov system setup`` will be on oakvar.readthedocs.io soon.

**Comment by Alex-Karmazin** [comment]
Thank you will try soon.

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin Documentation has been updated with installation and setup instructions. See https://oakvar.readthedocs.io.
