### ISSUE TITLE
Error during processing vcf file.

### ISSUE THREAD

**Issue by Alex-Karmazin** [rkimoakbioinformatics/oakvar#12]
I start job with file that was succesfuly processed with opencravat. But with oak var 2.5.10 it get folowing error:
"""
2022/08/01 20:53:11 oakvar               C:\ProgramData\Anaconda3\envs\openCravatPlugin\Scripts\oc run C:\open-cravat\jobs\default\220801-205305\antonkulaga_38_all_rsid_chrompos.vcf -a dbsnp prs -l hg38 --skip reporter --temp-files
2022/08/01 20:53:11 oakvar               started: Mon Aug  1 20:53:11 2022
2022/08/01 20:53:11 oakvar               conf file: None
2022/08/01 20:53:12 oakvar               input files: C:\open-cravat\jobs\default\220801-205305\antonkulaga_38_all_rsid_chrompos.vcf
2022/08/01 20:53:12 oakvar               input assembly: hg38
2022/08/01 20:53:12 oakvar               version: oakvar 2.5.10 C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar
2022/08/01 20:53:12 oakvar               version: dbsnp 154.0.2 C:\dev\python\openCravatPlugin\modules\annotators\dbsnp
2022/08/01 20:53:12 oakvar               version: prs None prs
2022/08/01 20:53:12 oakvar               version: hg38 1.10.2 C:\dev\python\openCravatPlugin\modules\mappers\hg38
2022/08/01 20:53:12 oakvar.converter     started: Mon Aug  1 20:53:12 2022
2022/08/01 20:53:12 oakvar.converter     Input file(s): C:\open-cravat\jobs\default\220801-205305\antonkulaga_38_all_rsid_chrompos.vcf
2022/08/01 20:53:17 oakvar.converter     input format: vcf
2022/08/01 20:53:17 oakvar.converter     Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\base\converter.py", line 26, in convert_file
    yield ln, line, self.convert_line(line)
  File "C:\dev\python\openCravatPlugin\modules\converters\vcf-converter\vcf-converter.py", line 216, in convert_line
    raise BadFormatError('All samples have the reference genotype.')
oakvar.exceptions.BadFormatError: All samples have the reference genotype.
2022/08/01 21:07:51 oakvar.converter     error lines: 1418835
2022/08/01 21:07:51 oakvar.converter     finished: Mon Aug  1 21:07:51 2022
2022/08/01 21:07:51 oakvar.converter     num input lines: 4660909
2022/08/01 21:07:51 oakvar.converter     runtime: 874.169
2022/08/01 21:07:52 oakvar               num_workers: 7
2022/08/01 21:07:57 oakvar               input line chunksize=675344 total number of input lines=4727413 number of chunks=7
"""

**Comment by Alex-Karmazin** [comment]
Also a got such traceback in console during this error:
"""
Running gene mapper...
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\base\mp_runners.py", line 73, in mapper_runner
    output = genemapper.run_as_slave(pos_no)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\base\mapper.py", line 316, in run_as_slave
    for ln, line, crv_data in self.reader.loop_data():
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\util\inout.py", line 146, in loop_data
    for lnum, toks in self._loop_data():
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\util\inout.py", line 212, in _loop_data
    csv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\Scripts\oc.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\__main__.py", line 169, in main
    handle_exception(e)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\__main__.py", line 151, in handle_exception
    raise e
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\__main__.py", line 162, in main
    ret = args.func(args)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\decorators.py", line 5, in change_args_for_cli
    ret = func(args)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\cli\run.py", line 7, in cli_run
    ret = run(args)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\decorators.py", line 32, in run_cli_func
    handle_exception(e)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\__main__.py", line 151, in handle_exception
    raise e
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\decorators.py", line 24, in run_cli_func
    ret = func(args)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\cli\run.py", line 43, in run
    return run(module.main())
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\nest_asyncio.py", line 38, in run
    return loop.run_until_complete(task)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\cli\run.py", line 531, in main
    raise self.exception
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\cli\run.py", line 469, in main
    await self.do_step_mapper()
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\cli\run.py", line 322, in do_step_mapper
    self.run_genemapper_mp()
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\cli\run.py", line 1296, in run_genemapper_mp
    job.get()
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
OverflowError: Python int too large to convert to C long
"""

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin Thanks. I'll look into it. The `BadFormatError` message is a misleading message which was suppressed by OpenCRAVAT. The overflow error was caused by the combination of a fix to handle very long annotation by some modules (thus, current OpenCRAVAT will err with such input and modules) and Python's using different maximum integer value in different systems. Both have been corrected in oakvar 2.5.11 I have just released. Please try that one. Also, vcf-converter 2.1.6 should be installed. Below are the steps.

```
pip install -U oakvar
ov store fetch
ov module update vcf-converter 
```

**Comment by antonkulaga** [comment]
here is the input file that caused that issue https://drive.google.com/file/d/1ebb1-opKU4F6UFLUsxyQnmjVCgtWeiYd/view?usp=sharing

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga Thanks. I have confirmed with your input file, oakvar v2.5.12, and vcf-converter 2.1.6 that the reported errors do not occur anymore. Let me know if it works for you as well.

**Comment by Alex-Karmazin** [comment]
I got many such errors:
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\websubmit\websubmit.py", line 687, in get_jobs
    job = await get_job(request, job_id)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\websubmit\websubmit.py", line 662, in get_job
    LooseVersion(job.info["open_cravat_version"])
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\distutils\version.py", line 52, in __lt__
    c = self._cmp(other)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\distutils\version.py", line 339, in _cmp
    if self.version == other.version:
AttributeError: 'LooseVersion' object has no attribute 'version'
"""
But they not interrupt process, so it is not critical for now. Thank you for quick support.

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin What is the Python version in your environment?

**Comment by Alex-Karmazin** [comment]
python 3.9

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin Thanks. Python 3.9 seems fine for using LooseVersion, but anyway LooseVersion is being deprecated in Python anyway, so I replaced it with `packaging.version` which is recommended by Python. The latest oakvar should not have that error.

**Comment by Alex-Karmazin** [comment]
I got some new tracebacks:
"""
Running annotators...
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\util\util.py", line 297, in load_class
    module = import_module(module_name)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'prs'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\util\util.py", line 297, in load_class
    module = import_module(module_name)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'prs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\util\util.py", line 307, in load_class
    loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\dev\\python\\openCravatPlugin\\prs\\prs.py'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\util\util.py", line 297, in load_class
    module = import_module(module_name)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\dev\python\openCravatPlugin\modules\annotators\dbsnp\dbsnp.py", line 6, in <module>
    from cravat.util import get_ucsc_bins, reverse_complement
ImportError: cannot import name 'get_ucsc_bins' from 'cravat.util' (unknown location)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\util\util.py", line 297, in load_class
    module = import_module(module_name)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\dev\python\openCravatPlugin\modules\annotators\dbsnp\dbsnp.py", line 6, in <module>
    from cravat.util import get_ucsc_bins, reverse_complement
ImportError: cannot import name 'get_ucsc_bins' from 'cravat.util' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\util\util.py", line 307, in load_class
    loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\dev\python\openCravatPlugin\modules\annotators\dbsnp\dbsnp.py", line 6, in <module>
    from cravat.util import get_ucsc_bins, reverse_complement
ImportError: cannot import name 'get_ucsc_bins' from 'cravat.util' (unknown location)
        annotator(s) finished in 1.679s
Running aggregator...
        Variants
"""

**Comment by Alex-Karmazin** [comment]
It seems my module that I'm working on "prs" did not load properly. But on opencravat it was working well.

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin I'll take a look.

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin Can you do `ov system md` and see if the output is a directory which has your `psr` module under `annotators`?

**Comment by Alex-Karmazin** [comment]
Yes it points to valid path. Here is this module if you need it. https://drive.google.com/file/d/1bKV_7AWKktXWB_aRtEt18UGyUSvchtA4/view?usp=sharing

**Comment by rkimoakbioinformatics** [comment]
On my system, `prs` module was successfully loaded and did not produce the module loading error. Just `division by zero` error was produced. What is the version obtained with `ov version`? The latest is 2.5.12.

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin Regarding the error with `dbsnp`, I have just published a new version `154.0.2.1` with a fix.

**Comment by Alex-Karmazin** [comment]
Now after I managed to update dbsnp I could come back to this issue. I have strange error:
"""
2022/08/10 20:38:56 prs                  module loading error for prs
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\util\util.py", line 297, in load_class
    module = import_module(module_name)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'prs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\util\util.py", line 306, in load_class
    loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\dev\\python\\openCravatPlugin\\prs\\prs.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\base\mp_runners.py", line 31, in annot_from_queue
    annotator_class = load_class(module.script_path, "Annotator")
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\util\util.py", line 308, in load_class
    raise ModuleLoadingError(module_name)
oakvar.exceptions.ModuleLoadingError: module loading error for prs
"""
It is the same custom module for PRS but I did not know why it searching file for this path 'C:\\dev\\python\\openCravatPlugin\\prs\\prs.py'. It may be cached somehow. There is no such path inside the code, and it was long ago when this path had any sense. Command "ov system md" has a valid path 
"D:\dev\oakVar\modules". Where I could find any clue why it search module in the old path?

**Comment by Alex-Karmazin** [comment]
Here is little bit more information:
"""
2022/08/10 20:38:50 oakvar               C:\ProgramData\Anaconda3\envs\openCravatPlugin\Scripts\oc run C:\open-cravat\jobs\default\220810-203847\longevity_snps_1000genom.vcf -a dbsnp prs -l hg38 --skip reporter --temp-files
2022/08/10 20:38:50 oakvar               started: Wed Aug 10 20:38:49 2022
2022/08/10 20:38:50 oakvar               conf file: None
2022/08/10 20:38:50 oakvar               input files: C:\open-cravat\jobs\default\220810-203847\longevity_snps_1000genom.vcf
2022/08/10 20:38:50 oakvar               input assembly: hg38
2022/08/10 20:38:50 oakvar               version: oakvar 2.5.23 C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar
2022/08/10 20:38:50 oakvar               version: dbsnp 154.0.2.1 D:\dev\oakVar\modules\annotators\dbsnp
2022/08/10 20:38:50 oakvar               version: prs None C:\dev\python\openCravatPlugin\prs
2022/08/10 20:38:50 oakvar               version: hg38 1.10.2 D:\dev\oakVar\modules\mappers\hg38
2022/08/10 20:38:50 oakvar.converter     started: Wed Aug 10 20:38:50 2022
2022/08/10 20:38:50 oakvar.converter     Input file(s): C:\open-cravat\jobs\default\220810-203847\longevity_snps_1000genom.vcf
2022/08/10 20:38:50 oakvar.converter     version: vcf-converter==2.1.6
2022/08/10 20:38:50 oakvar.converter     input format: vcf
2022/08/10 20:38:51 oakvar.converter     error lines: 0
2022/08/10 20:38:51 oakvar.converter     finished: Wed Aug 10 20:38:51 2022
2022/08/10 20:38:51 oakvar.converter     num input lines: 2797
2022/08/10 20:38:51 oakvar.converter     runtime: 0.303
2022/08/10 20:38:51 oakvar               num_workers: 7
2022/08/10 20:38:51 oakvar               input line chunksize=624 total number of input lines=4369 number of chunks=7
2022/08/10 20:38:55 oakvar               num_workers: 7
"""

**Comment by antonkulaga** [comment]
So far this issue is a blocker for our PRS module

**Comment by rkimoakbioinformatics** [comment]
`ov run` can accept the path to a module as an option to `-a` argument. For example, `ov run input.vcf -a /path/to/prs`. This way, testing and using custom modules outside of the system modules directory is easy. `-a` as a custom path has priority over `-a` as a module name.

Thus, if there is `prs` directory in the current working directory, the error can happen.

If there is no more `prs` in the current working directory and the error still occurs, this can happen if `ov gui` has been running while the custom `prs` directory was removed.

To test these possibilities:

- `ov run ... -a prs` command in a directory in which there is no `prs` directory
- Restarting `ov gui` in a directory in which there is no `prs` directory

Does any of the above make sense in your case?

**Comment by Alex-Karmazin** [comment]
Thank you, it helped. There was prs folder in my project where I put everything regarding this functionality. I just rename it and everything starts working. By the way in OakVar secondary_data structure is changed compared with OpenCravat. Do you plan to have backward compatibility, or it will be incompatible with it?

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin I plan to keep backward compatibility and thought that it has been kept. Can you describe the discrepancy a bit so that I can start investigation?

**Comment by Alex-Karmazin** [comment]
In OpenCravat I write secondary_data['dbsnp'][0]['rsid'] but now I have to change it to secondary_data['dbsnp']['rsid'] in order to get it working.

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin Ah, got it. I pushed a new release oakvar 2.5.27 which restored the backward compatibility. Please try that one with the old format for secondary_data.

**Comment by Alex-Karmazin** [comment]
Unfortunatly new errors appeared:
"""
No module named 'vcf'
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\Scripts\oc.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\oakvar\__main__.py", line 169, in main
    handle_exception(e)
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\oakvar\__main__.py", line 151, in handle_exception
    raise e
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\oakvar\__main__.py", line 162, in main
    ret = args.func(args)
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\oakvar\decorators.py", line 5, in change_args_for_cli
    ret = func(args)
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\oakvar\cli\run.py", line 7, in cli_run
    ret = run(args)
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\oakvar\decorators.py", line 32, in run_cli_func
    handle_exception(e)
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\oakvar\__main__.py", line 151, in handle_exception
    raise e
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\oakvar\decorators.py", line 24, in run_cli_func
    ret = func(args)
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\oakvar\cli\run.py", line 43, in run
    return run(module.main())
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\nest_asyncio.py", line 35, in run
    return loop.run_until_complete(task)
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\oakvar\cli\run.py", line 531, in main
    raise self.exception
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\oakvar\cli\run.py", line 468, in main
    await self.do_step_converter()
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\oakvar\cli\run.py", line 299, in do_step_converter
    self.run_converter()
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\oakvar\cli\run.py", line 1123, in run_converter
    self.numinput, self.converter_format = converter.run()
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\oakvar\base\cravat_convert.py", line 517, in run
    converter.setup(f)  # type: ignore
  File "D:\dev\oakVar\modules\converters\vcf-converter\vcf-converter.py", line 55, in setup
    import vcf
ModuleNotFoundError: No module named 'vcf'
Process Process-4:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\oakvar\websubmit\websubmit.py", line 1148, in fetch_job_queue
    main_loop.run_until_complete(job_worker_main())
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\oakvar\websubmit\websubmit.py", line 1125, in job_worker_main
    job_tracker.clean_jobs(None)
  File "C:\ProgramData\Anaconda3\envs\cruise_misle\lib\site-packages\oakvar\websubmit\websubmit.py", line 1080, in clean_jobs
    job_ids.remove(uid)
ValueError: list.remove(x): x not in list
"""

**Comment by Alex-Karmazin** [comment]
After modules update, these errors disappears. But still it is incompatible with opencravat secondary_data['dbsnp'][0]['rsid'] is not working with [0] only secondary_data['dbsnp']['rsid'] works.

**Comment by rkimoakbioinformatics** [comment]
I see. Have you updated OakVar with "pip install -U oakvar" as well?

**Comment by Alex-Karmazin** [comment]
Yes now I have Version: 2.5.23

**Comment by antonkulaga** [comment]
@Alex-Karmazin just don't be lazy with updates, I am using 2.5.27 already

**Comment by Alex-Karmazin** [comment]
I updated to Version: 2.5.27 and now it is compatible with opencravat.
