### ISSUE TITLE
JSON Error in stacktrace

### ISSUE THREAD

**Issue by Alex-Karmazin** [rkimoakbioinformatics/oakvar#15]
I got some JSON Errors in my stacktrace on launch:
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\websubmit\websubmit.py", line 203, in job_status
    raise e
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\websubmit\websubmit.py", line 198, in job_status
    statusjson = json.load(f)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

"""

**Comment by Alex-Karmazin** [comment]
And one invalid version, I am using OakVar 2.5.14:
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\websubmit\websubmit.py", line 683, in get_jobs
    job = await get_job(request, job_id)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\websubmit\websubmit.py", line 658, in get_job
    Version(job.info["open_cravat_version"])
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\packaging\version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
"""

**Comment by rkimoakbioinformatics** [comment]
Thanks. I'll take a look.

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin The error messages were by-products of the situation where `.status.json` file was empty somehow. Those errors do not affect the overall function of the GUI except the problem job. I'll release an improved version shortly.

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin I have just released oakvar v2.5.17 in which the issue has been fixed. It's a rather temporary measure so that `ov gui` will launch despite any problem job, since the GUI will get overhaul in the near future.

**Comment by antonkulaga** [comment]
@Alex-Karmazin is it still relevant or you can close?

**Comment by rkimoakbioinformatics** [comment]
I believe that the issue was fixed. Closing for now. Please let me know if it still exists.
