### ISSUE TITLE
Error during setup in  excelreporter

### ISSUE THREAD

**Issue by Alex-Karmazin** [rkimoakbioinformatics/oakvar#30]
After command "ov system setup" I got error:
"""
Installing required PyPI packages...
Requirement already satisfied: xlsxwriter in c:\programdata\anaconda3\envs\opencravatplugin\lib\site-packages (3.0.3)
[2022:09:04 15:56:49] Downloading code archive of excelreporter:2.2.0...
[2022:09:04 15:56:51] Extracting code archive of excelreporter:2.2.0...
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\Scripts\ov.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\__main__.py", line 169, in main
    handle_exception(e)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\__main__.py", line 151, in handle_exception
    raise e
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\__main__.py", line 162, in main
    ret = args.func(args)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\decorators.py", line 5, in change_args_for_cli
    ret = func(args)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\cli\system.py", line 7, in cli_system_setup
    setup(args)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\decorators.py", line 32, in run_cli_func
    handle_exception(e)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\__main__.py", line 151, in handle_exception
    raise e
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\decorators.py", line 24, in run_cli_func
    ret = func(args)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\cli\system.py", line 14, in setup
    setup_system(args)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\system\__init__.py", line 32, in setup_system
    ret = installbase(args)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\decorators.py", line 32, in run_cli_func
    handle_exception(e)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\__main__.py", line 151, in handle_exception
    raise e
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\decorators.py", line 24, in run_cli_func
    ret = func(args)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\cli\module.py", line 376, in installbase
    ret = install(m_args)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\decorators.py", line 32, in run_cli_func
    handle_exception(e)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\__main__.py", line 151, in handle_exception
    raise e
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\decorators.py", line 24, in run_cli_func
    ret = func(args)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\cli\module.py", line 229, in install
    ret = install_module(
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\module\__init__.py", line 557, in install_module
    raise e
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\module\__init__.py", line 525, in install_module
    extract_code_or_data(kind="code", args=args)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\module\__init__.py", line 367, in extract_code_or_data
    zf = zipfile.ZipFile(args.get(f"{kind}_zipfile_path"))
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\zipfile.py", line 1257, in __init__
    self._RealGetContents()
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\zipfile.py", line 1324, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
"""

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin Sorry about that. I accidentally messed with the module. It should be back online now (v2.2.1).
