### ISSUE TITLE
[BUG] Errors on "ov system setup" command

### ISSUE THREAD

**Issue by marfantyk** [rkimoakbioinformatics/oakvar#35]
System configuration file: /home/marfantyk/.oakvar/conf/system.yml
User configuration file: /home/marfantyk/.oakvar/oakvar.yml.
No store update to fetch
No store update to fetch
No store update to fetch
cravat-converter==1.1.2 is already installed. Use -f/--force to overwrite
casecontrol==1.2.0 is already installed. Use -f/--force to overwrite
The following modules will be installed:
- excelreporter==2.2.1
- gencode==41.0.2
- go==2021.02.04
- hg38wgs==2020.03.13
- oldcravat-converter==1.1.2
- stdoutreporter==1.2.1
- tagsampler==1.1.5
- textreporter==2.2.0
- varmeta==1.0.0
- vcf-converter==2.3.0
- vcfinfo==1.1.5
- vcfreporter==4.0.1
- wgbase==1.2.0
- wgcircossummary==2.1.0
- wgcodingvsnoncodingsummary==1.4.0
- wggosummary==2.5.0
- wghg19==1.0.3
- wglollipop==2.3.0
- wgncrna==1.1.0
- wgndex==1.2.0
- wgnote==2.1.0
- wgrankscore==1.1.0
- wgsosamplesummary==2.2.0
- wgsosummary==1.7.0
- wgvcfinfo==1.0.3
installing excelreporter...
[2022:09:30 01:00:26] Starting to install excelreporter:2.2.1...
Following PyPI dependencies should be met before installing excelreporter.
- xlsxwriter
Installing required PyPI packages...
Requirement already satisfied: xlsxwriter in /home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages (3.0.3)
[2022:09:30 01:00:29] Downloading code archive of excelreporter:2.2.1...
Traceback (most recent call last):
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/download/download.py", line 208, in _fetch_file
    u = urllib.request.urlopen(req, timeout=timeout)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/bin/ov", line 8, in <module>
    sys.exit(main())
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/__main__.py", line 169, in main
    handle_exception(e)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/__main__.py", line 151, in handle_exception
    raise e
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/__main__.py", line 162, in main
    ret = args.func(args)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/decorators.py", line 5, in change_args_for_cli
    ret = func(args)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/cli/system.py", line 7, in cli_system_setup
    setup(args)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/decorators.py", line 32, in run_cli_func
    handle_exception(e)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/__main__.py", line 151, in handle_exception
    raise e
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/decorators.py", line 24, in run_cli_func
    ret = func(args)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/cli/system.py", line 14, in setup
    setup_system(args)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/system/__init__.py", line 32, in setup_system
    ret = installbase(args)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/decorators.py", line 32, in run_cli_func
    handle_exception(e)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/__main__.py", line 151, in handle_exception
    raise e
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/decorators.py", line 24, in run_cli_func
    ret = func(args)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/cli/module.py", line 374, in installbase
    ret = install(m_args)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/decorators.py", line 32, in run_cli_func
    handle_exception(e)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/__main__.py", line 151, in handle_exception
    raise e
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/decorators.py", line 24, in run_cli_func
    ret = func(args)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/cli/module.py", line 223, in install
    ret = install_module(
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/module/__init__.py", line 577, in install_module
    raise e
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/module/__init__.py", line 542, in install_module
    if not download_code_or_data(kind="code", args=args):
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/module/__init__.py", line 345, in download_code_or_data
    download(urls[i], part_path)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/oakvar/util/download.py", line 10, in download
    download_util.download(url, fpath, kind="file", verbose=False, replace=True)
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/download/download.py", line 119, in download
    _fetch_file(
  File "/home/marfantyk/micromamba/envs/oakvar-longevity/lib/python3.10/site-packages/download/download.py", line 277, in _fetch_file
    raise RuntimeError(
RuntimeError: Error while fetching file https://c7i1.va21.idrivee2-1.com/oakvar-modules/reporters/excelreporter/2.2.0/excelreporter__2.2.1__code.zip. Dataset fetching aborted.
Error: <urlopen error timed out>

**Comment by rkimoakbioinformatics** [comment]
@Marfantyk Thanks. I'll take a look.

**Comment by rkimoakbioinformatics** [comment]
@Marfantyk It could have been a glitch in the server hosting the download files. As I test now, the problem module is installed without an error. Can you try `ov system setup` again?

**Comment by marfantyk** [comment]
@rkimoakbioinformatics just tried to do it again and got the same error.

**Comment by rkimoakbioinformatics** [comment]
@Marfantyk Is this file accessible/downloadable on your computer? https://c7i1.va21.idrivee2-1.com/oakvar-modules/reporters/excelreporter/2.2.0/excelreporter__2.2.1__code.zip

**Comment by antonkulaga** [comment]
I think the problem is that this file is on a server that is blocked in some countries. I remember @winternewt had the same problem. However, I am not totally sure.
```
wget  https://c7i1.va21.idrivee2-1.com/oakvar-modules/reporters/excelreporter/2.2.0/excelreporter__2.2.1__code.zip
```
works for me

**Comment by marfantyk** [comment]
@rkimoakbioinformatics yes, I can't download it. So the problem is in blocking in my country. I will try to use vpn tomorrow to setup it. Thank you!

**Comment by rkimoakbioinformatics** [comment]
@Marfantyk My pleasure. Hope that you'll be able to download with the vpn.

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga I see. I'll look into it.

**Comment by rkimoakbioinformatics** [comment]
@Marfantyk I have just published the excelreporter to a different server. Hope this helps and let me know if it still does not work.

**Comment by marfantyk** [comment]
@rkimoakbioinformatics yes, excelreporter was downloaded, but now there is the same problem for gencode.

Here is log:

[2022:09:30 18:19:40] Downloading code archive of gencode:41.0.2...
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marfantyk/.local/lib/python3.8/site-packages/download/download.py", line 208, in _fetch_file
    u = urllib.request.urlopen(req, timeout=timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marfantyk/.local/bin/ov", line 8, in <module>
    sys.exit(main())
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/__main__.py", line 169, in main
    handle_exception(e)
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/__main__.py", line 151, in handle_exception
    raise e
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/__main__.py", line 162, in main
    ret = args.func(args)
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/decorators.py", line 5, in change_args_for_cli
    ret = func(args)
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/cli/system.py", line 7, in cli_system_setup
    setup(args)
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/decorators.py", line 32, in run_cli_func
    handle_exception(e)
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/__main__.py", line 151, in handle_exception
    raise e
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/decorators.py", line 24, in run_cli_func
    ret = func(args)
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/cli/system.py", line 14, in setup
    setup_system(args)
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/system/__init__.py", line 32, in setup_system
    ret = installbase(args)
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/decorators.py", line 32, in run_cli_func
    handle_exception(e)
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/__main__.py", line 151, in handle_exception
    raise e
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/decorators.py", line 24, in run_cli_func
    ret = func(args)
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/cli/module.py", line 374, in installbase
    ret = install(m_args)
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/decorators.py", line 32, in run_cli_func
    handle_exception(e)
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/__main__.py", line 151, in handle_exception
    raise e
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/decorators.py", line 24, in run_cli_func
    ret = func(args)
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/cli/module.py", line 223, in install
    ret = install_module(
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/module/__init__.py", line 577, in install_module
    raise e
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/module/__init__.py", line 542, in install_module
    if not download_code_or_data(kind="code", args=args):
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/module/__init__.py", line 345, in download_code_or_data
    download(urls[i], part_path)
  File "/home/marfantyk/.local/lib/python3.8/site-packages/oakvar/util/download.py", line 10, in download
    download_util.download(url, fpath, kind="file", verbose=False, replace=True)
  File "/home/marfantyk/.local/lib/python3.8/site-packages/download/download.py", line 119, in download
    _fetch_file(
  File "/home/marfantyk/.local/lib/python3.8/site-packages/download/download.py", line 277, in _fetch_file
    raise RuntimeError(
RuntimeError: Error while fetching file https://c7i1.va21.idrivee2-1.com/oakvar-modules/mappers/gencode/gencode__41.0.2__code.zip. Dataset fetching aborted.
Error: <urlopen error timed out>

**Comment by marfantyk** [comment]
@rkimoakbioinformatics I kept installing with vpn and it worked fine. Then I tried to install some modules without vpn. There were  problems with some of them too. But, again, vpn fixes this problem. Do you need a list of such modules?

**Comment by rkimoakbioinformatics** [comment]
@Marfantyk  I'm glad that at least using a VPN helped. Yes, such a list would be helpful.

**Comment by antonkulaga** [comment]
@Marfantyk it looks no longer relevan, please close
