### ISSUE TITLE
[BUG] Error on "ov run exampleinput -a clinvar -t vcf"

### ISSUE THREAD

**Issue by lopatich** [rkimoakbioinformatics/oakvar#37]
2022/11/27 23:59:37 oakvar.mapper        input file: /home/pavlov_stud/second/project/exampleinput.crv
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 576, in _handle_results
    task = get()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
ModuleNotFoundError: No module named 'pysqlite2'

 - OS: Ubuntu
 - OakVar Version v2.6.3

**Comment by rkimoakbioinformatics** [comment]
Hi @lopatich , sorry for this late reply. I was busy with the new release (v2.7). The error seems to be related to your system environment, since OakVar does not use pysqlite2. Did you install OakVar with `pip install oakvar`? It should use `sqlite3` module already included in Python 3. Some suggestions are:

* Try installing some libraries as recommended is https://github.com/jupyterhub/jupyterhub/issues/464 and https://stackoverflow.com/questions/45565290/jupyter-missing-sqlite3-and-pysqlite2.
* Try a clean Python 3 environment with conda or virtualenv (Python 3.8 or higher).

Let me know if the above did not work.

**Comment by rkimoakbioinformatics** [comment]
@lopatich Hi, do you still experience the issue?
