### ISSUE TITLE
ov gui leads to crashes

### ISSUE THREAD

**Issue by antonkulaga** [rkimoakbioinformatics/oakvar#5]
when I run ov gui I see
```
Traceback (most recent call last):
  File "/home/antonkulaga/micromamba/envs/dna-seq/lib/python3.10/site-packages/oakvar/webstore/webstore.py", line 110, in get_remote_manifest
    oc_manifest = get_manifest()
  File "/home/antonkulaga/micromamba/envs/dna-seq/lib/python3.10/site-packages/oakvar/store/db.py", line 25, in encl_func
    ret = func(*args, conn=conn, cursor=cursor, **kwargs)
  File "/home/antonkulaga/micromamba/envs/dna-seq/lib/python3.10/site-packages/oakvar/store/db.py", line 543, in get_manifest
    cursor.execute(q)
sqlite3.OperationalError: no such table: summary
```
I did not activate the store due to verififivation email never sent issues, but I assume basic modules should work without issues even without any verifications.

**Comment by rkimoakbioinformatics** [comment]
ov uses an internal cache db to have the module information to show on the web store page. No store account verification -> no fetch of the cache db. I'm fixing the verification issue. Afterwards, this issue will be gone. I'll get back to you shortly.

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga I manually verified your account for now. please try `ov system setup --clean` and then `ov gui`.

**Comment by rkimoakbioinformatics** [comment]
@antonkulaga The server has been fixed. `ov system setup --clean` and then `ov gui` should work.

**Comment by antonkulaga** [comment]
I confirm, it works now
