### ISSUE TITLE
[BUG] Issue with annotators (cadd, hgvs)

### ISSUE THREAD

**Issue by MariosGvr** [rkimoakbioinformatics/oakvar#57]
Hi, 
thank you so much for this amazing tool! I'm encountering issues with a couple of annotators. Despite searching online, I haven't been able to resolve these problems myself. Thank you for taking the time to help.

**Describe the bug**
I recently installed oakvar to annotate SNP calls from DeepVariant. I am having same issues with certain annotators. In more detail:

1. CADD annotator: I have no problem installing cadd_exome but cadd gives an error while trying to download the necessary data:
```
(oakvar) marios@node3:~/my_data/snp_analysis/grch38$ ov module install cadd
No store update to fetch
The following modules will be installed:
- cadd==1.6.0
Proceed? ([y]/n) > y
[2024:04:04 09:34:00] Starting to install cadd==1.6.0...
Installing required PyPI packages...
Requirement already satisfied: pytabix in /home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages (0.1)
[2024:04:04 09:34:06] Downloading code archive of cadd==1.6.0...
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
[2024:04:04 09:34:08] Extracting code archive of cadd==1.6.0...
[2024:04:04 09:34:08] Downloading data of cadd==1.6.0...
[2024:04:04 09:34:08] Downloading cadd data file 0 / 87...
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
corrupt download /home/marios_homedir/my_data/tools/oakvar/modules/temp/cadd/cadd__1.6.0__data.zip000 at https://storage.oakvar.com/oakvar-modules/annotators/cadd/1.6.0/cadd__1.6.0__data.zip000
Traceback (most recent call last):
  File "/home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/lib/module/__init__.py", line 841, in install_module
    raise ModuleInstallationError(module_name)
oakvar.lib.exceptions.ModuleInstallationError: cadd was not properly installed. Consider 'ov module install cadd'.
cadd was not properly installed. Consider 'ov module install cadd'.
Following modules were not installed due to problems:
- cadd
```

2. HGVS: This module is installed with no errors, but when I try to run the annotator it reports it does not exist. Also hgvs is not reported as installed by `ov module ls`, but wghgvs is. The error:
```
(oakvar) marios@node3:~/my_data/snp_analysis/grch38$ ov module install hgvs
No store update to fetch
The following modules will be installed:
- hgvs==1.0.7
Proceed? ([y]/n) > y
[2024:04:04 09:34:47] Starting to install hgvs==1.0.7...
[2024:04:04 09:34:47] Downloading code archive of hgvs==1.0.7...
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
[2024:04:04 09:34:48] Extracting code archive of hgvs==1.0.7...
[2024:04:04 09:34:48] Downloading data of hgvs==1.0.7...
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
[2024:04:04 09:34:59] Extracting data of hgvs==1.0.7...
[2024:04:04 09:35:00] finished installation of hgvs==1.0.7
Installed hgvs.
(oakvar) marios@node3:~/my_data/snp_analysis/grch38$ ov run $vcf -a hgvs  -t vcf -d ${out_dir} --mp 5
module [hgvs] does not exist. Possible solutions: 'ov system setup' and/or 'ov module install hgvs'

```

**How Oakvar was installed**

oakvar was installed the following way:
```
mamba create -n oakvar oakvar
mamba activate oakvar
export OV_ROOT_DIR=/home/marios_homedir/my_data/tools/oakvar
export OV_LOGS_DIR=/home/marios_homedir/my_data/tools/oakvar/oakvar_logs
export OV_LIFTOVER_DIR=/home/marios_homedir/my_data/tools/oakvar/conf/liftover
export OV_MODULES_DIR=/home/marios_homedir/my_data/tools/oakvar/modules
export OV_JOBS_DIR=/home/marios_homedir/my_data/tools/oakvar/jobs
export OV_LOG_DIR=/home/marios_homedir/my_data/tools/oakvar/logs
ov system setup
.
.
.
System configuration file: /home/marios_homedir/my_data/tools/oakvar/conf/system.yml
User configuration file: /home/marios_homedir/.oakvar/oakvar.yml.
Logged in as myemail@email.com
Setting up store cache...
Fetching store cache 1/5...
Fetching store cache 2/5...
Fetching store cache 3/5...
Fetching store cache 4/5...
Fetching store cache 5/5...
Finalizing fetch...
.
.
.
Done setting up the system.
```
I was successfully able to run annotations using any other library I have tried so far.

**Desktop:**
 - OS: Red Hat Enterprise Linux 8.8
 - OakVar Version: 2.9.92
 
 Thank you again!

**Comment by rkimoakbioinformatics** [comment]
Hi, I'll check with the CADD module. 

Regarding `hgvs` module, HGVS notation for cDNA change and amino acid change is already included in the output of the default mapper, `gencode` module.

**Comment by rkimoakbioinformatics** [comment]
@MariosGvr CADD v1.7.0 has been released. Please try with `ov module install cadd` and `ov run -a cadd`.

**Comment by MariosGvr** [comment]
Unfortunately, I am getting a new error regarding PyPi packages.

Running: `ov module install cadd`
Output:
```
No store update to fetch
The following modules will be installed:
- cadd==1.7.0
Proceed? ([y]/n) > y
[2024:04:10 12:41:55] Starting to install cadd==1.7.0...
Installing required PyPI packages...
Requirement already satisfied: duckdb in /home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages (0.7.1)
ERROR: Could not find a version that satisfies the requirement bisect (from versions: none)
ERROR: No matching distribution found for bisect
Following PyPI dependencies could not be installed.
- bisect
Failed in installing pypi package dependence
Traceback (most recent call last):
  File "/home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/lib/module/__init__.py", line 769, in install_module
    raise ModuleInstallationError(module_name)
oakvar.lib.exceptions.ModuleInstallationError: cadd was not properly installed. Consider 'ov module install cadd'.
cadd was not properly installed. Consider 'ov module install cadd'.
Following modules were not installed due to problems:
- cadd
```
Thank you for trying to resolve this issue!

**Comment by rkimoakbioinformatics** [comment]
Sorry, there was a small bug (no need to install `bisect`). `cadd` v1.7.1 has been released with a fix. Please try `ov module install cadd` again.

**Comment by MariosGvr** [comment]
Thank you for attending the issue.
Since the update, I am getting the following error while fetching store cache:

```
mamba activate oakvar
export OV_ROOT_DIR=/home/marios_homedir/my_data/tools/oakvar
export OV_LOGS_DIR=/home/marios_homedir/my_data/tools/oakvar/oakvar_logs
export OV_LIFTOVER_DIR=/home/marios_homedir/my_data/tools/oakvar/conf/liftover
export OV_MODULES_DIR=/home/marios_homedir/my_data/tools/oakvar/modules
export OV_JOBS_DIR=/home/marios_homedir/my_data/tools/oakvar/jobs
export OV_LOG_DIR=/home/marios_homedir/my_data/tools/oakvar/logs
ov system setup
.
.
.
Logged in as myemail@email.com
Setting up store cache...
Fetching store cache 1/5...
Fetching store cache 2/5...
Fetching store cache 3/5...
Traceback (most recent call last):
  File " /home/marios_homedir/mambaforge/envs/oakvar/bin/ov", line 8, in <module>
    sys.exit(main())
  File " /home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/__main__.py", line 244, in main
    handle_exception(e)
  File " /home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/__main__.py", line 221, in handle_exception
    raise e
  File " /home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/__main__.py", line 236, in main
    ret = func(args)
  File " /home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/cli/__init__.py", line 65, in change_args_for_cli
    ret = func(args)
  File " /home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/cli/system.py", line 47, in cli_system_setup
    setup(args)
  File  /home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/cli/__init__.py", line 86, in run_cli_func
    handle_exception(e)
  File " /home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/__main__.py", line 221, in handle_exception
    raise e
  File " /home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/cli/__init__.py", line 79, in run_cli_func
    ret = func(args, **kwargs)
  File " /home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/cli/system.py", line 54, in setup
    return setup(**args)
  File " /home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/api/system.py", line 79, in setup
    return setup_system(
  File " /home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/lib/system/__init__.py", line 106, in setup_system
    setup_ov_store_cache(
  File " /home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/lib/store/ov/__init__.py", line 81, in setup_ov_store_cache
    fetch_ov_store_cache(
  File " /home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/lib/store/db.py", line 66, in encl_func
    ret = func(*args, conn=conn, cursor=cursor, **kwargs)
  File " /home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/lib/store/db.py", line 553, in fetch_ov_store_cache
    fetch_readme_cache(publish_time=publish_time, outer=outer)
  File " /home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/lib/store/db.py", line 66, in encl_func
    ret = func(*args, conn=conn, cursor=cursor, **kwargs)
  File " /home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/lib/store/db.py", line 717, in fetch_readme_cache
    with open(fpath, "wb") as wf:
FileNotFoundError: [Errno 2] No such file or directory: ' /home/marios_homedir/my_data/tools/oakvar/conf/readme/ov/converters/gvf-converter'
```

Even after the above error I do `ov module install cadd` and it works properly apart from the initial:
```
Fetching store cache 1/5...
Fetching store cache 2/5...
Fetching store cache 3/5...
Fetching store update failed:

>>[Errno 2] No such file or directory: '/home/marios_homedir/my_data/tools/oakvar/conf/readme/ov/converters/gvf-converter'.

Continuing with the current store cache.
The following modules will be installed:
- cadd==1.7.1
Proceed? ([y]/n) >
[2024:04:11 08:04:24] Starting to install cadd==1.7.1...
[2024:04:11 08:04:24] Downloading code archive of cadd==1.7.1...
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
[2024:04:11 08:04:26] Extracting code archive of cadd==1.7.1...
[2024:04:11 08:04:26] Downloading data of cadd==1.7.1...
[2024:04:11 08:04:26] Downloading cadd data file 0 / 394...
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
[2024:04:11 08:04:29] Downloading cadd data file 1 / 394
...
[2024:04:11 08:24:12] Downloading cadd data file 393 / 394...
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
[2024:04:11 08:24:14] Extracting data of cadd==1.7.1...
[2024:04:11 08:24:53] finished installation of cadd==1.7.1
Installed cadd.
```

I tried to fix this by running `pip install -U oakvar`, `ov module update`, `ov update`. Also I tried running `ov system setup --clean`, removed the `conf`, `logs `and `jobs` directories and run `ov system setup` again. I tried running `ov store account delete` to setup my store account from scratch again but I got the following error:
```
(oakvar) marios@node3:~$ ov store account delete
Fail (CREDENTIAL_TOO_OLD_LOGIN_AGAIN)
(oakvar) marios@node3:~$ ov store account login
usage: ov account [-h] {create,delete,change,check,reset} ...
ov account: error: argument {create,delete,change,check,reset}: invalid choice: 'login' (choose from 'create', 'delete', 'change', 'check', 'reset')
```

**Comment by rkimoakbioinformatics** [comment]
Hi Marios, sorry about that. There was a small glitch in the server and it was fixed. As you noted, it didn't affect the installation of `cadd` module itself. Next time when you run `ov module install`, `ov store fetch`, or `ov system setup`, the error should not happen.

**Comment by MariosGvr** [comment]
Hey!
Thank you, now it works. However, it seems there is an issue with the CADD annotation.
After installing CADD I run:  `ov run $vcf -a cadd `
Output:
```
...
...
2024/04/11 13:28:51 oakvar               starting annotator step...
2024/04/11 13:28:51 oakvar               num_workers: 1
2024/04/11 13:28:52 cadd                 started CADD (cadd)
2024/04/11 13:28:52 cadd                 started: Thu Apr 11 13:28:52 2024
2024/04/11 13:28:52 cadd                 IO Error: Trying to read a database file with version number 64, but we can only read version 43.
The database file was created with an newer version of DuckDB.

The storage of DuckDB is not yet stable; newer versions of DuckDB cannot read old database files and vice versa.
The storage will be stabilized when version 1.0 releases.

For now, we recommend that you load the database file in a supported version of DuckDB, and use the EXPORT DATABASE command followed by IMPORT DATABASE on the current version of DuckDB.

See the storage page for more information: https://duckdb.org/internals/storage
Traceback (most recent call last):
  File "/home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/lib/base/annotator.py", line 532, in run
    self.base_setup()
  File "/home/marios_homedir/mambaforge/envs/oakvar/lib/python3.10/site-packages/oakvar/lib/base/annotator.py", line 674, in base_setup
    self.setup()
  File "/home/marios_homedir/my_data/tools/oakvar/modules/annotators/cadd/cadd.py", line 9, in setup
    self.conn = duckdb.connect(str(db_path))
duckdb.IOException: IO Error: Trying to read a database file with version number 64, but we can only read version 43.
The database file was created with an newer version of DuckDB.

The storage of DuckDB is not yet stable; newer versions of DuckDB cannot read old database files and vice versa.
The storage will be stabilized when version 1.0 releases.

For now, we recommend that you load the database file in a supported version of DuckDB, and use the EXPORT DATABASE command followed by IMPORT DATABASE on the current version of DuckDB.

See the storage page for more information: https://duckdb.org/internals/storage
2024/04/11 13:28:53 oakvar               annotator step finished in 1.890s
2024/04/11 13:28:53 oakvar               starting aggregator step...
...
...
```
Thank you a lot for your help!

**Comment by rkimoakbioinformatics** [comment]
Hi, most likely your system has an old DuckDB. Please install the newest DuckDB with "pip install -U duckdb" and try again.

**Comment by rkimoakbioinformatics** [comment]
OakVar v2.9.95 has been released as well, which will handle PyPI package dependencies better so that you don't have to update dependency packages such as DuckDB manually.

**Comment by MariosGvr** [comment]
Thank you so much for all your help! 
Everything works great now!

**Comment by rkimoakbioinformatics** [comment]
Great. Please feel free to let me know if there is anything you wish about OakVar. My email is rkim at oakbioinformatics.com.
