### ISSUE TITLE
Error on starting job

### ISSUE THREAD

**Issue by Alex-Karmazin** [rkimoakbioinformatics/oakvar#6]
I got error on start anatation job with dbsnp and my custom anotator. Error apears just in first 10 seconds after vcf file uploaded. In wcravat.log nothing special in log I got:
"""
2022/07/30 17:34:45 oakvar               C:\ProgramData\Anaconda3\envs\openCravatPlugin\Scripts\oc run C:\open-cravat\jobs\default\220730-173438\antonkulaga_38_all_rsid_chrompos.vcf -a dbsnp prs -l hg38 --skip reporter --temp-files
2022/07/30 17:34:45 oakvar               started: Sat Jul 30 17:34:45 2022
2022/07/30 17:34:45 oakvar               conf file: None
2022/07/30 17:34:45 oakvar               input files: C:\open-cravat\jobs\default\220730-173438\antonkulaga_38_all_rsid_chrompos.vcf
2022/07/30 17:34:45 oakvar               input assembly: hg38
2022/07/30 17:34:45 oakvar               version: oakvar 2.5.4 C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar
2022/07/30 17:34:45 oakvar               version: dbsnp 154.0.2 C:\dev\python\openCravatPlugin\modules\annotators\dbsnp
"""
But in console I got this:
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\Scripts\oc.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\__main__.py", line 169, in main
    handle_exception(e)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\__main__.py", line 151, in handle_exception
    raise e
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\__main__.py", line 162, in main
    ret = args.func(args)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\decorators.py", line 5, in change_args_for_cli
    ret = func(args)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\cli\run.py", line 7, in cli_run
    ret = run(args)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\decorators.py", line 32, in run_cli_func
    handle_exception(e)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\__main__.py", line 151, in handle_exception
    raise e
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\decorators.py", line 24, in run_cli_func
    ret = func(args)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\cli\run.py", line 43, in run
    return run(module.main())
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\nest_asyncio.py", line 38, in run
    return loop.run_until_complete(task)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\cli\run.py", line 519, in main
    raise self.exception
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\cli\run.py", line 451, in main
    self.log_versions()
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\oakvar\cli\run.py", line 262, in log_versions
    f"version: {module.name} {module.conf['version']} {os.path.dirname(module.script_path)}"
KeyError: 'version'
"""
I running it on windows 10 on anaconda. Befor thet I use opencravat and it works fine on this anotators and vcf file.

**Comment by rkimoakbioinformatics** [comment]
Thanks. I'll take a look into it.

**Comment by rkimoakbioinformatics** [comment]
I have just published oakvar v2.5.5 which has a fix for it. Please try that one.

**Comment by Alex-Karmazin** [comment]
Thank you it works fine.
