### ISSUE TITLE
no favicon.ico error in wcravat.log

### ISSUE THREAD

**Issue by Alex-Karmazin** [rkimoakbioinformatics/oakvar#7]
I found this error in log file:
"""
2022/07/30 17:35:12: Unhandled exception
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\aiohttp\web_protocol.py", line 514, in start
    resp, reset = await task
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\asyncio\futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\asyncio\tasks.py", line 328, in __wakeup
    future.result()
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\asyncio\tasks.py", line 258, in __step
    result = coro.throw(exc)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\aiohttp\web_protocol.py", line 460, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\aiohttp\web_protocol.py", line 613, in finish_response
    await prepare_meth(request)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\site-packages\aiohttp\web_fileresponse.py", line 142, in prepare
    st: os.stat_result = await loop.run_in_executor(None, filepath.stat)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\asyncio\futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\asyncio\tasks.py", line 328, in __wakeup
    future.result()
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\ProgramData\Anaconda3\envs\openCravatPlugin\lib\pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
FileNotFoundError: [WinError 2] Не удается найти указанный файл: 'C:\\ProgramData\\Anaconda3\\envs\\openCravatPlugin\\Lib\\site-packages\\oakvar\\cli\\..\\favicon.ico'
"""

**Comment by rkimoakbioinformatics** [comment]
I have just published oakvar v2.5.5 which has a fix for this issue. Please try this new version.
